disabled_rules:
- trailing_whitespace
- force_cast
- force_unwrapping
- identifier_name
- line_length
- shorthand_operator
- trailing_whitespace
- type_name
- function_parameter_count
- function_body_length
- nesting

opt_in_rules:
- mark
- empty_count
- empty_string

excluded:
- KeepGoEat-iOS/Application
