name: iOS Test on develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: echo Hello, world!
    - name: Run tests
      run: | 
        xcodebuild clean test -project KeepGoEat-iOS/KeepGoEat-iOS/KeepGoEat-iOS.xcodeproj/ -scheme ExGithubAction -destination "platform=iOS Simulator,name=iPhone 11"
